@extends('layouts.app')
@section('content')
<div class="heading"><div><h1>{{ $product->name }}</h1><p>{{ $product->sku }} · {{ $product->category->name }} · BDT {{ $product->unit_price }}</p></div><strong class="stock">{{ $product->stock_on_hand }} units</strong></div>
@if(auth()->user()->isManager())
<section class="panel"><h2>Product details</h2><form method="post" action="{{ route('products.update',$product) }}" class="grid-form">@csrf @method('PATCH')
<input type="hidden" name="expected_version" value="{{ $product->version }}"><label>Category<select name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($category->id===$product->category_id)>{{ $category->name }}</option>@endforeach</select></label><label>SKU<input name="sku" value="{{ $product->sku }}" required></label><label>Name<input name="name" value="{{ $product->name }}" required></label><label>Unit price<input name="unit_price" value="{{ $product->unit_price }}" required></label><label>Reorder level<input type="number" name="reorder_level" value="{{ $product->reorder_level }}" required></label><button>Save version {{ $product->version }}</button></form>
<form method="post" action="{{ $product->archived_at ? route('products.restore',$product) : route('products.archive',$product) }}" class="inline-form">@csrf<input type="hidden" name="expected_version" value="{{ $product->version }}"><button class="secondary">{{ $product->archived_at ? 'Restore product' : 'Archive product' }}</button></form></section>
<div class="two-col">
<section class="panel"><h2>Receive stock</h2><form method="post" action="{{ route('products.restocks',$product) }}" class="stack">@csrf<input type="hidden" name="request_key" value="{{ $restockForm['request_key'] }}"><label>Quantity<input type="number" name="quantity" value="{{ $restockForm['quantity'] }}" min="1" max="1000000" required></label><label>Reason<input name="note" value="{{ $restockForm['note'] }}" maxlength="500" required></label><button>Record receipt</button></form></section>
<section class="panel"><h2>Correct stock</h2><form method="post" action="{{ route('products.adjustments',$product) }}" class="stack">@csrf<input type="hidden" name="request_key" value="{{ $adjustmentForm['request_key'] }}"><input type="hidden" name="expected_version" value="{{ $adjustmentForm['expected_version'] }}"><label>Signed change<input type="number" name="quantity_delta" value="{{ $adjustmentForm['quantity'] }}" min="-1000000" max="1000000" required></label><label>Reason<input name="note" value="{{ $adjustmentForm['note'] }}" maxlength="500" required></label><button>Record correction</button></form></section>
</div>
@if($hasStockInput)<p>Retry unchanged with the preserved request key. To review a stale version or enter a different operation, <a href="{{ route('products.show',$product) }}">reset the stock forms</a>.</p>@endif
@endif
<h2>Stock movement history</h2><div class="table-wrap"><table><thead><tr><th>Time (Asia/Dhaka)</th><th>Reason</th><th>Change</th><th>Result</th><th>Actor</th><th>Sale</th><th>Note</th></tr></thead><tbody>@forelse($movements as $m)<tr><td>{{ $m->created_at->timezone(config('nexastock.display_timezone'))->format('Y-m-d H:i:s T') }}</td><td>{{ $m->reason }}</td><td>{{ $m->quantity_delta > 0 ? '+' : '' }}{{ $m->quantity_delta }}</td><td>{{ $m->resulting_stock }}</td><td>{{ $m->actor->name }}</td><td>@if($m->saleItem)<a href="{{ route('sales.show',$m->saleItem->sale_id) }}">NS-{{ $m->saleItem->sale_id }}</a>@else — @endif</td><td>{{ $m->note }}</td></tr>@empty<tr><td colspan="7">No movements yet; stock should be zero.</td></tr>@endforelse</tbody></table></div>{{ $movements->links() }}
@endsection
